### ISSUE TITLE
TypeError: the JSON object must be str, not 'bytes' при импорте коллекции иконок

### ISSUE THREAD

**Issue by gggrafff** [kebasyaty/django-editor-ymaps#4]
Добрый день. Возникает ошибка при импорте коллекции иконок. Python 3.5.

```
ERROR Internal Server Error: /djeym/ajax-import-icon-collection/
Traceback (most recent call last):
  File "/home/ants/Projects/AutoCulture/venv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ants/Projects/AutoCulture/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ants/Projects/AutoCulture/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ants/Projects/AutoCulture/venv/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ants/Projects/AutoCulture/venv/lib/python3.5/site-packages/djeym/decorators.py", line 36, in wrapper
    return view_func(self, request, *args, **kwargs)
  File "/home/ants/Projects/AutoCulture/venv/lib/python3.5/site-packages/djeym/views.py", line 803, in dispatch
    return super(AjaxImportIconCollection, self).dispatch(request, *args, **kwargs)
  File "/home/ants/Projects/AutoCulture/venv/lib/python3.5/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ants/Projects/AutoCulture/venv/lib/python3.5/site-packages/djeym/views.py", line 775, in post
    collection_json = json.loads(collection_json)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
ERROR "POST /djeym/ajax-import-icon-collection/ HTTP/1.1" 500 20321
```

**Comment by gggrafff** [comment]
Аналогичная ошибка при добавлении тайлов. Нужно сделать преобразование к str после чтения файла.

**Comment by gggrafff** [comment]
нужно поправить:
collection_json = json.loads(collection_json.decode('utf-8')) в строке 775
source_list = json.loads(source_list.decode('utf-8')) в строке 861
